### ISSUE TITLE
Key generation from KeyDataConfig

### ISSUE THREAD

**Issue by melowe** [Consensys/tessera#204]
`com.github.nexus.config.adapters.KeyDataAdapter` needs to be interpreted with the create pairs code in KeyManager located in the nexus-app module. The KeyManger code that does this needs to be in the config module and all of this needs to happen in the config module. 

```
    @Override
    public KeyData unmarshal(KeyData keyData) throws Exception {

        if (keyData.hasKeys()) {
            return keyData;
        }

        //TODO: Generate key pairs from and create populated keyData
        KeyDataConfig keyDataConfig = KeyDataConfigStore.INSTANCE.pop();

        return new KeyData(keyDataConfig, null, null);
    }
```
The private and public keys need generating from the KeyDataConfig object and storing on the KeyData

**Comment by prd-fox** [comment]
Keys can now be generated using input files for the configuration of the private keys
