### ISSUE TITLE
Support for FUSE file system directory support

### ISSUE THREAD

**Issue by melowe** [Consensys/tessera#276]
There's a legacy file system data format. Our present code tries to leverage jdbc as much as possible. 

Assuming that is appetite for directory system datastore support the choice is find a jdbc driver that allows us to do this which will give us the benefit of less code changes or add specialised support by way of a FileSystemDAO or something. This will mean more code and having a less homogenous code base.

**Comment by namtruong** [comment]
Task parked as discussed. For users that used legacy file system storage, there will be instructions on how to migrate data.
For requirements to support stuff like fuse, amazon s3, etc... there will be a separate task to use proper driver,...
