### ISSUE TITLE
Test If Vagrant will run under 4 GB for Tessera integrated 7 nodes example. Last test was with 6 GB.

### ISSUE THREAD

**Issue by Krish1979** [Consensys/tessera#293]
Test memory profiling and update in readme

**Comment by chris-j-h** [comment]
4 GB is too unreliable so have kept at 6 GB.  Have added details of the vagrant memory limit and how to run 7nodes with only 5 nodes to the qourum-examples README.  This will allow machines with limited memory to run the examples.
