### ISSUE TITLE
Add CLI override for config.json

### ISSUE THREAD

**Issue by Krish1979** [Consensys/tessera#295]

**Comment by melowe** [comment]
Which overrides?


usage: tessera -configfile <PATH> [-keygen <PATH>] [-pidfile <PATH>]
    --alwaysSendTo.keyBytes <BYTE[]...>                         Override option for alwaysSendTo.keyBytes , type: byte[]
 -configfile <PATH>                                             Path to node configuration file
    --jdbc.password <STRING>                                    Override option for jdbc.password , type: String
    --jdbc.url <STRING>                                         Override option for jdbc.url , type: String
    --jdbc.username <STRING>                                    Override option for jdbc.username , type: String
 -keygen <PATH>                                                 Path to private key config for generation of missing key files
    --keys.keyData.config.data.aopts.algorithm <STRING>         Override option for keys.keyData.config.data.aopts.algorithm , type: String
    --keys.keyData.config.data.aopts.iterations <INTEGER>       Override option for keys.keyData.config.data.aopts.iterations , type: Integer
    --keys.keyData.config.data.aopts.memory <INTEGER>           Override option for keys.keyData.config.data.aopts.memory , type: Integer
    --keys.keyData.config.data.aopts.parallelism <INTEGER>      Override option for keys.keyData.config.data.aopts.parallelism , type: Integer
    --keys.keyData.config.data.asalt <STRING>                   Override option for keys.keyData.config.data.asalt , type: String
    --keys.keyData.config.data.bytes <STRING>                   Override option for keys.keyData.config.data.bytes , type: String
    --keys.keyData.config.data.password <STRING>                Override option for keys.keyData.config.data.password , type: String
    --keys.keyData.config.data.sbox <STRING>                    Override option for keys.keyData.config.data.sbox , type: String
    --keys.keyData.config.data.snonce <STRING>                  Override option for keys.keyData.config.data.snonce , type: String
    --keys.keyData.config.type <PRIVATEKEYTYPE>                 Override option for keys.keyData.config.type , type: PrivateKeyType
    --keys.keyData.privateKey <STRING>                          Override option for keys.keyData.privateKey , type: String
    --keys.keyData.privateKeyPath <PATH>                        Override option for keys.keyData.privateKeyPath , type: Path
    --keys.keyData.publicKey <STRING>                           Override option for keys.keyData.publicKey , type: String
    --keys.keyData.publicKeyPath <PATH>                         Override option for keys.keyData.publicKeyPath , type: Path
    --keys.passwordFile <PATH>                                  Override option for keys.passwordFile , type: Path
    --keys.passwords <STRING[]...>                              Override option for keys.passwords , type: String[]
 -output <arg>                                                  Generate updated config file with generated keys
    --peer.url <STRING>                                         Override option for peer.url , type: String
 -pidfile <PATH>                                                Path to pid file
    --server.hostName <STRING>                                  Override option for server.hostName , type: String
    --server.influxConfig.dbName <STRING>                       Override option for server.influxConfig.dbName , type: String
    --server.influxConfig.hostName <STRING>                     Override option for server.influxConfig.hostName , type: String
    --server.influxConfig.port <INTEGER>                        Override option for server.influxConfig.port , type: Integer
    --server.influxConfig.pushIntervalInSecs <LONG>             Override option for server.influxConfig.pushIntervalInSecs , type: Long
    --server.port <INTEGER>                                     Override option for server.port , type: Integer
    --server.sslConfig.clientKeyStore <PATH>                    Override option for server.sslConfig.clientKeyStore , type: Path
    --server.sslConfig.clientKeyStorePassword <STRING>          Override option for server.sslConfig.clientKeyStorePassword , type: String
    --server.sslConfig.clientTlsCertificatePath <PATH>          Override option for server.sslConfig.clientTlsCertificatePath , type: Path
    --server.sslConfig.clientTlsKeyPath <PATH>                  Override option for server.sslConfig.clientTlsKeyPath , type: Path
    --server.sslConfig.clientTrustCertificates <PATH[]...>      Override option for server.sslConfig.clientTrustCertificates , type: Path[]
    --server.sslConfig.clientTrustMode <SSLTRUSTMODE>           Override option for server.sslConfig.clientTrustMode , type: SslTrustMode
    --server.sslConfig.clientTrustStore <PATH>                  Override option for server.sslConfig.clientTrustStore , type: Path
    --server.sslConfig.clientTrustStorePassword <STRING>        Override option for server.sslConfig.clientTrustStorePassword , type: String
    --server.sslConfig.generateKeyStoreIfNotExisted <BOOLEAN>   Override option for server.sslConfig.generateKeyStoreIfNotExisted , type: boolean
    --server.sslConfig.knownClientsFile <PATH>                  Override option for server.sslConfig.knownClientsFile , type: Path
    --server.sslConfig.knownServersFile <PATH>                  Override option for server.sslConfig.knownServersFile , type: Path
    --server.sslConfig.serverKeyStore <PATH>                    Override option for server.sslConfig.serverKeyStore , type: Path
    --server.sslConfig.serverKeyStorePassword <STRING>          Override option for server.sslConfig.serverKeyStorePassword , type: String
    --server.sslConfig.serverTlsCertificatePath <PATH>          Override option for server.sslConfig.serverTlsCertificatePath , type: Path
    --server.sslConfig.serverTlsKeyPath <PATH>                  Override option for server.sslConfig.serverTlsKeyPath , type: Path
    --server.sslConfig.serverTrustCertificates <PATH[]...>      Override option for server.sslConfig.serverTrustCertificates , type: Path[]
    --server.sslConfig.serverTrustMode <SSLTRUSTMODE>           Override option for server.sslConfig.serverTrustMode , type: SslTrustMode
    --server.sslConfig.serverTrustStore <PATH>                  Override option for server.sslConfig.serverTrustStore , type: Path
    --server.sslConfig.serverTrustStorePassword <STRING>        Override option for server.sslConfig.serverTrustStorePassword , type: String
    --server.sslConfig.tls <SSLAUTHENTICATIONMODE>              Override option for server.sslConfig.tls , type: SslAuthenticationMode
    --unixSocketFile <PATH>                                     Override option for unixSocketFile , type: Path
    --useWhiteList <BOOLEAN>                                    Override option for useWhiteList , type: boolean

**Comment by melowe** [comment]
Perhaps easier to read

   --alwaysSendTo.keyBytes <BYTE[]...>    
 -configfile <PATH>            
    --jdbc.password <STRING> 
    --jdbc.url <STRING>     
    --jdbc.username <STRING>  
 -keygen <PATH>          
    --keys.keyData.config.data.aopts.algorithm <STRING> 
    --keys.keyData.config.data.aopts.iterations <INTEGER>   
    --keys.keyData.config.data.aopts.memory <INTEGER> 
    --keys.keyData.config.data.aopts.parallelism <INTEGER>   
    --keys.keyData.config.data.asalt <STRING>        
    --keys.keyData.config.data.bytes <STRING>         
    --keys.keyData.config.data.password <STRING>      
    --keys.keyData.config.data.sbox <STRING>
    --keys.keyData.config.data.snonce <STRING>   
    --keys.keyData.config.type <PRIVATEKEYTYPE>       
    --keys.keyData.privateKey <STRING>                 
    --keys.keyData.privateKeyPath <PATH>                 
    --keys.keyData.publicKey <STRING>          
    --keys.keyData.publicKeyPath <PATH>
    --keys.passwordFile <PATH>     
    --keys.passwords <STRING[]...>
 -output <arg>                                       
    --peer.url <STRING>           
 -pidfile <PATH>                  
    --server.hostName <STRING>  
    --server.influxConfig.dbName <STRING> 
    --server.influxConfig.hostName <STRING>  
    --server.influxConfig.port <INTEGER> 
    --server.influxConfig.pushIntervalInSecs <LONG> 
    --server.port <INTEGER>  
    --server.sslConfig.clientKeyStore <PATH> 
    --server.sslConfig.clientKeyStorePassword <STRING>  
    --server.sslConfig.clientTlsCertificatePath <PATH> 
    --server.sslConfig.clientTlsKeyPath <PATH> 
    --server.sslConfig.clientTrustCertificates <PATH[]...> 
    --server.sslConfig.clientTrustMode <SSLTRUSTMODE> 
    --server.sslConfig.clientTrustStore <PATH> 
    --server.sslConfig.clientTrustStorePassword <STRING> 
    --server.sslConfig.generateKeyStoreIfNotExisted <BOOLEAN> 
    --server.sslConfig.knownClientsFile <PATH> 
    --server.sslConfig.knownServersFile <PATH>
    --server.sslConfig.serverKeyStore <PATH> 
    --server.sslConfig.serverKeyStorePassword <STRING>
    --server.sslConfig.serverTlsCertificatePath <PATH> 
    --server.sslConfig.serverTlsKeyPath <PATH> 
    --server.sslConfig.serverTrustCertificates <PATH[]...>
    --server.sslConfig.serverTrustMode <SSLTRUSTMODE> 
    --server.sslConfig.serverTrustStore <PATH>
    --server.sslConfig.serverTrustStorePassword <STRING>  
    --server.sslConfig.tls <SSLAUTHENTICATIONMODE>        
    --unixSocketFile <PATH>                                
    --useWhiteList <BOOLEAN>
