### ISSUE TITLE
Ported Constellation bug into tessera where -filename has no value

### ISSUE THREAD

**Issue by melowe** [Consensys/tessera#380]
When a user elects to generate a key from the tessera cli s/he apparently can provide an empty file name. Normal usage is : 

`tessera -keygen -filename somefile,someotherfile`

apparently its desirable to also support 

`tessera -keygen -filename`

In this case we've now gone to the effort of defining the filename option and then not provided any values for it, the reasonable exception would be that the user is then informed that they haven't defined the file name(s) s/he wishes to use to generate the keys. 

**Once we clarify that having no args for -filename is incorrect we need to remove support for it.**

**Comment by jpmsam** [comment]
@melowe @Krish1979  That's incorrect, no need to support the `-filename` flag without a filename being passed.

**Comment by Krish1979** [comment]
yes we will remove that in next release

**Comment by Krish1979** [comment]
This is fixed
